# Generated by Django 2.1.4 on 2019-02-21 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_auto_20190219_1113'),
        ('reagents', '0002_auto_20181122_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.Group'),
        ),
    ]
